### ISSUE TITLE
Pull requests Italian translation

### ISSUE THREAD

**Issue by stepanz70** [raspberrypilearning/cd-sebento-htmlcss-1#8]
I,
My name is Stefano (Coderdojo Milan), I have made a Pull requests with the Italian translation.
I hope you like it and you are going to use soon.
Thank you.

**Comment by ninaszymor** [comment]
Hi @stepanz70 :-) Thank you so much for submitting the Italian translation. At the beginning of this year, we introduced a new process for translating our resources, which means we are no longer able to accept translations via GitHub. Please take a look at raspberrypi.org/translate, where you can register as a volunteer and join our translation community - we have an excellent team of Italian translators and would love to have you on board. We ca then use your translation by taking it through the new process. 

Hope this is helpful, let me know if you have any questions or problems.

Nina (Translation Manager for Raspberry Pi)
